### PR TITLE
Implementation of EventsOverTime class

### PR DESCRIPTION
**Pull request by tmns**
Hi all 👋

So this PR grew out of our need to be able to calculate populations of users like so:

- How many users were using an android device between the dates of 1-12-19 and 4-12-19?
- How many users were using an ios device between February and May?

I was surprised when I realized that Bitmapist didn't already implement such a feature. Especially considering it is similar in logic to the `get_cohort_row` and `YearEvents` implementations. Is there a reason why?

My provided implementation includes a new `events` class `EventsOverTime`. Its `__init__` function takes an `event_name`, `scale`, `dt`, and `delta` argument, where:
- `scale` is a `string` equal to `'day', 'week', 'month', or 'year'`. 
- `dt` is a `datetime` object representing the date from which you would like to begin the calculation.
- `delta` is an `int` representing how many days, weeks, months, or years you want to calculate. 

Based on the given `scale`, the `__init__` function then makes the appropriate bitmapist events calls `delta + 1` times, `append`ing the results of each call to a list `events`, which is then ran through `BitOpOr` at the end.

So, for example, going back to our first problem above, if we had the following populations:
```
>>> len(b.DayEvents('os:android').delta(-6))
66
>>> len(b.DayEvents('os:android').delta(-7))
240
>>> len(b.DayEvents('os:android').delta(-8))
319
>>> len(b.DayEvents('os:android').delta(-9))
255
```

We can calculate the population over the four days like so:
```
>>> six_days_ago = datetime.datetime.utcnow() - datetime.timedelta(6)
>>> len(b.EventsOverTime('os:android', 'day', six_days_ago, 3))
880
```

This is a contrived example of course, it's more useful when calculating larger spans and dealing with stranger date constraints. 

As of now it lives as an implementation only in our code base - but I think it would be a useful addon for everyone to be able to use without manually doing it like I did! If there's a specific reason why this was never implemented though - I'd love to hear it!

If this is eventually merged I would also be glad to edit the `README` with appropriate documentation!/

Thanks!

P.S. I created this branch from the `with-check-for-keys` branch 😬so it also includes that commit!

### CODE REVIEW

**Comment by imankulov** [comment]
Hey @tmns 

Thanks a lot for the contribution and sorry for the delayer review! With this saying, frankly, I don't think we are ready to accept this pull request. One of the reasons is that I can't justify to myself why we introduce a new class, which is a mere wrapper around BitOpOr.

One of the alternative variants would be a utility function returning a list of events for the given range. These events could be grouped together with BitOpOr or a different operator.

**Comment by tmns** [comment]
Hi @imankulov

Thank you for the feedback - I agree with your conclusion that introducing a new class is a little overkill. As per your suggestion, I reworked the class into a function in `core.py` - when you get some time take a look and let me know if it would be of any use implemented that way instead.

Hope your week's off to a good start!

**Comment by imankulov** [comment]
Hi @tmns 

Frankly, I'm still not convinced. Sorry for not sharing with you more doubts in the beginning, or not to make them clearer.

Things that keep worrying me.

- Introduction a whole set of constants  'day', 'week', 'month', or 'year' in the API. Something which we don't have at the moment. This makes API incoherent, and besides, the case where a user passes to the API an unrecognized string (for example, "daily" instead of "day") is not properly processed
- Implementation-wise, repeating almost the same code for different types of objects makes it error-prone for further modifications and harder to extend. For example, in your pull request, there's already a copy-paste typo: you wrote`detla` instead of `delta`.
 - I ask myself, why `BitOpOr` is hardcoded? There is a valid use-case when you want to test whether a user was active, say, every week during the last six weeks creating a streak, and yet somehow we have a function for the OR operation, but not for AND. Again, this makes API looks inconsistent.
- The name of the function, along with the list of parameters, doesn't tell the reader, what it does. Without reading the documentation, the call `b.get_events_in_range('device:android', dt=date, delta=36, scale='day')` leaves a lot of questions. What is `dt`, is it the beginning or the end of the range? What is delta and scale? What type of object the function returns and what's the meaning of it?

I still feel like creating an ad-hoc function inside your own code is more straightforward than trying to use `get_events_in_range`.

I should admit that everything I wrote about the API consistency may not be true for the currently exposed API, and this makes my complaints sounding like arbitrary rants. Let me reassure you, it's not because I don't like your work or want to discourage you from your contributions. Quite the opposite, I'm happy and humbled to see that our work is good useful that people find it worthwhile improving and extending it. I encourage myself and others to make code cleaner, and API more clear than it was when we started the project.

**Comment by tmns** [comment]
Hi @imankulov 

Wow - thank you so much for the in depth reply, especially with everything going on right now - your time and effort is very appreciated. 

No worries - your points definitely do not sound like arbitrary rants. They make a lot of sense and provide me with great feedback for refactoring the version of it I'm using locally. In fact, the points you made here are even helpful / applicable to my general programming practices - so thank you again very much!

I think it's quite clear that this can be closed now. I hope you're all okay and staying healthy!

**Pull request closed without merging**
